safe: false
highlighter: rouge
lsi: false
permalink: /:categories/:title
url: https://randomwits.com
markdown: kramdown
title: Random Wits
port: 4000
future: false
mod: "%"
encoding: "utf-8"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
gems: [jekyll-paginate]
paginate: 3
not_paginated_categories:
  - 'projects'
author:
  name: "Tushar Sharma"
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: randomwits
# Social usernames/URLs
twitter_username: tshrocks
title_image: "https://i.imgur.com/4HK7q8C.jpg"
description: "Welcome to Randomwits, my digital nest."