safe: false
highlighter: rouge
lsi: false
permalink: /:categories/:title
url: https://randomwits.com
markdown: kramdown
title: RandomWits
port: 4000
future: false
mod: "%"
encoding: "utf-8"
tagline: life is too short for a diary
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gzip
  - jekyll-include-cache
  - jekyll-spaceship
  - jekyll-maps
maps:
  google:
    api_key: ENV['GOOGLE_MAP_API_KEY']
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
- .jekyll-cache
- raw/
algolia:
  application_id: '0XJJCPHPDY'
  index_name: randomwits
  public_key: 618de85a39ad952f6e4c506d3c752777
  files_to_exclude:
    - tag/*
    - blog/*
gems: [jekyll-paginate]
paginate: 3
not_paginated_categories:
  - 'projects'
author:
  name: "Tushar Sharma"
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: randomwits
# Social usernames/URLs
twitter_username: tshrocks
title_image: "https://i.imgur.com/4HK7q8C.jpg"
description: "Welcome to Randomwits, my digital nest."
