safe: false
highlighter: rouge
lsi: false
permalink: /:categories/:title
url: http://randomwits.com
markdown: kramdown
title: Random Wits
port: 4000
future: false
mod: "%"
kramdown:
  math_engine: mathjax
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo, rsquo, ldquo, rdquo
  input: GFM
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
gems: [jekyll-paginate]
paginate: 3
not_paginated_categories:
  - 'projects'
author:
  name: "Tushar Sharma"
