safe: false
highlighter: Pygments
lsi: false
permalink: /:categories/:title
url: http://randomwits.com
markdown: kramdown 
title: Random Wits
port: 4000
future: false
mod: "%"
kramdown:
  math_engine: mathjax
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
gems: [jekyll-paginate]
paginate: 4 
not_paginated_categories:
  - 'projects'
