safe: false
highlighter: rouge
lsi: false
permalink: /:categories/:title
url: http://randomwits.com
markdown: kramdown
title: Random Wits
port: 4000
future: false
mod: "%"
encoding: "utf-8"
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
gems: [jekyll-paginate]
paginate: 3
not_paginated_categories:
  - 'projects'
author:
  name: "Tushar Sharma"