safe: true
highlighter: pygments
lsi: false
permalink: /:categories/:title
url: http://randomwits.com
markdown: kramdown 
title: Random Wits
port: 4000
future: false
mod: "%"
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
- branch.txt
- .gitignore
paginate: 3
not_paginated_categories:
  - 'projects'
